(lang dune 2.0)

(name rin_rocks)

(version 0.0)

(maintainers "hi@rin.rocks")

(generate_opam_files true)

(package
  (name rin_rocks)
  (synopsis "rin_rocks")
  (description "Rin.rocks")
  (depends
    dream
    lwt_ppx
    ))
