name: "build"
on:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GH_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: r17
          # If you chose signing key for write access
          # signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          # If you chose API tokens for write access OR if you have a private cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: pre-commit-hooks,nix-community
          skipPush: ${{ !(github.ref == 'refs/heads/main' && github.event_name == 'push') }}
      - run: nix flake show
      - run: nix flake check
      - run: nix build .#frontend
      - run: nix build .#backend
