name: "build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
      with:
        github_access_token: ${{ secrets.GH_TOKEN }}
    - run: nix flake check
    - run: nix build .#frontend
    - run: nix build .#backend
